- name: Start service awx, if not started
  service:
    name: awx.service
    state: started
    enabled: true
  when: service is defined and service == True

- name: Check if docker-compose.yml file exists
  stat:
    path: '{{ project_dir }}/awx/docker-compose.yml'
  register: result
  when: service is not defined or service == False

- name: Run Docker Compose down
  docker_compose:
    project_src: '{{ project_dir }}/awx'
    state: absent
    remove_volumes: '{{ remove_volumes }}'
  when: (service is not defined or service == False) and result.stat.exists

- name: Start service awx, if not started
  service:
    name: awx.service
    state: stopped
    enabled: false
  when: service is defined and service == True

- name: Copy the awx.service file
  file:
    path: '/etc/systemd/system/awx.service'
    state: absent
  when: service is defined and service == True

- name: Delete folder is 'state' is absent
  file:
    path: '{{ project_dir }}/awx'
    state: absent