- name: Check variables
  assert:
    that:
      - secret_key is defined

- name: Create the project directory
  file:
    path: '{{ project_dir }}/awx'
    state: directory

- name: Copy the environment.sh file
  template:
    src: environment.sh.j2
    dest: '{{ project_dir }}/awx/environment.sh'
    mode: 0600

- name: Copy the credentials.py file
  template:
    src: credentials.py.j2
    dest: '{{ project_dir }}/awx/credentials.py'
    mode: 0600

- name: Copy the docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: '{{ project_dir }}/awx/docker-compose.yml'
    mode: 0600
  register: compose_config

- name: Copy the awx.service file
  template:
    src: awx.service.j2
    dest: '/etc/systemd/system/awx.service'
    mode: 0600

- name: Render SECRET_KEY file
  copy:
    content: '{{ secret_key }}'
    dest: '{{ project_dir }}/awx/SECRET_KEY'
    mode: 0600
  register: awx_secret_key

- name: Start service awx, if not started
  service:
    name: awx.service
    state: started
    enabled: true
  when: service is defined and service == True

- name: Start the containers
  docker_compose:
    project_src: '{{ project_dir }}/awx'
    restarted: '{{ compose_config is changed }}'
    build: yes
    state: present
  register: awx_compose_start
  when: service is not defined and service == False

- name: 'Update CA trust in awx web container'
  shell: docker exec {{ awx_web_host }} '/usr/bin/update-ca-trust'
  when: (awx_compose_config is defined and awx_compose_config.changed) or awx_compose_start.changed or (service is defined and service == True)

- name: 'Update CA trust in awx task container'
  shell: docker exec {{ awx_task_host }} '/usr/bin/update-ca-trust'
  when: (awx_compose_config is defined and awx_compose_config.changed) or awx_compose_start.changed or (service is defined and service == True)